version: '3.3'
services:
  jenkins-casc:
    container_name: jenkins-casc
    restart: always
    image: registry.cn-shenzhen.aliyuncs.com/infrastlabs/jenkins-casc:latest
    # command: xx
    network_mode: "host"
    # ports:
    #   - 8080:8080
    #   - 50000:50000
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock