    FROM docker:17.12.1-ce as src
# FROM jenkins/jenkins:2.204.1
FROM registry.cn-shenzhen.aliyuncs.com/k-spe/dvp-jenkins:v204.6-j9-020-tzone8
MAINTAINER sam <devops@pcitech.com>

# Delay for CasC + disable install wizard
ENV JAVA_OPTS="-Dio.jenkins.plugins.casc.ConfigurationAsCode.initialDelay=9000 -Djenkins.install.runSetupWizard=false -Dorg.jenkinsci.main.modules.sshd.SSHD.hostName=127.0.0.1"

# JCasC Plugin pointer to config/secret values
ENV SECRETS="/var/jenkins_home/"

USER root
COPY --from=src /usr/local/bin/docker usr/local/bin/docker

#libltdl: docker use.
RUN apk add libltdl subversion make

# Add minimum jenkins setup
ADD init.groovy.d /usr/share/jenkins/ref/init.groovy.d
ADD dsl /usr/share/jenkins/ref/dsl
COPY scriptApproval.xml /var/jenkins_home/scriptApproval.xml

# Install plugins
COPY plugins-full-genClean.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt

